# https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html
output.elasticsearch.hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
setup.kibana.host: "elk:5601"

metricbeat:
  modules:
#    - module: system
#      metricsets:
#        - cpu             # CPU usage
#        - load            # CPU load averages
#        - memory          # Memory usage
#        - network         # Network IO
#        - process         # Per process metrics
#        - process_summary # Process summary
#        - uptime          # System Uptime
#        - socket_summary  # Socket summary
#        - core           # Per CPU core usage
#        - diskio         # Disk IO
#        - filesystem     # File system usage for each mountpoint
#        #- fsstat         # File system summary metrics
#        #- raid           # Raid
#        #- socket         # Sockets and connection info (linux only)
#        - service        # systemd service information
#      enabled: true
#      period: 10s
#      processes: [ '.*' ]
#
#      # Configure the mount point of the hostâ€™s filesystem for use in monitoring a host from within a container
#      #hostfs: "/hostfs"
#
#      # Configure the metric types that are included by these metricsets.
#      cpu.metrics: [ "percentages","normalized_percentages" ]  # The other available option is ticks.
#      core.metrics: [ "percentages" ]